### https://github.com/Huachao/vscode-restclient/issues/523
### https://github.com/Huachao/vscode-restclient#environment-variables
### if run using wsl2 @hostname = [::1]
@hostname = localhost
@port = 8080
@protocol = http
@host = {{protocol}}://{{hostname}}:{{port}}

### Get All Categories
GET {{host}}/categories HTTP/1.1

### Get Category by id
GET {{host}}/categories/1 HTTP/1.1

### Get Category by id ERROR
GET {{host}}/categories/99999 HTTP/1.1

### Create Category
POST {{host}}/categories HTTP/1.1
content-type: application/json

{
    "name": "Games"
}