### https://github.com/Huachao/vscode-restclient/issues/523
### https://github.com/Huachao/vscode-restclient#environment-variables
### if run using wsl2 @hostname = [::1]
@hostname = localhost
@port = 8080
@protocol = http
@host = {{protocol}}://{{hostname}}:{{port}}

### Get All Categories
GET {{host}}/categories HTTP/1.1

### Get All Categories Paged
GET {{host}}/categories?page=1 HTTP/1.1

### Get Category by id
GET {{host}}/categories/1 HTTP/1.1

### Get Category by id ERROR
GET {{host}}/categories/99999 HTTP/1.1

### Create Category
POST {{host}}/categories HTTP/1.1
content-type: application/json

{
    "name": "Games"
}

### Update Category
PUT {{host}}/categories/1 HTTP/1.1
content-type: application/json

{
    "name": "Books and Articles"
}

### Update Category with id not found
PUT {{host}}/categories/9999999 HTTP/1.1
content-type: application/json

{
    "name": "Books and Articles"
}

### DELETE Category by id
DELETE {{host}}/categories/4 HTTP/1.1

### Get All products Paged
GET {{host}}/products?page=1&orderBy=price&direction=DESC HTTP/1.1

### Get product by id
GET {{host}}/products/1 HTTP/1.1

### Create product
POST {{host}}/products HTTP/1.1
content-type: application/json

{
  "name": "PS5",
  "description": "The new generation PS5 video game",
  "price": 600.0,
  "imgUrl": "",
  "date": "2020-07-20T10:00:00Z",
  "categories": [
    {
      "id": 1
    },
    {
      "id": 3
    }
  ]
}

### Update product
PUT {{host}}/products/26 HTTP/1.1
content-type: application/json

{
  "name": "Updated product name",
  "description": "Updated product description",
  "price": 600.0,
  "imgUrl": "",
  "date": "2020-07-20T10:00:00Z",
  "categories": [
    {
      "id": 1
    },
    {
      "id": 3
    }
  ]
}

### DELETE product by id
DELETE {{host}}/products/26 HTTP/1.1